spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_account
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
    druid:
      filters: wall,stat
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.css,*.ico,/druid/*'
      aop-patterns: com.itcast.admin.*
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true  
    
  jdbc:
    template:
      query-timeout: 3 
      
      
      
mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
       